"""add_page_type_and_menu_page_id

Revision ID: 17568737f224
Revises: a94db48af463
Create Date: 2026-05-25 13:48:01.996604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17568737f224'
down_revision: Union[str, Sequence[str], None] = 'a94db48af463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('page_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_menus_page_id_pages', 'menus', 'pages', ['page_id'], ['id'], ondelete='SET NULL')
    op.add_column('pages', sa.Column('type', sa.String(length=20), nullable=True))
    op.execute("UPDATE pages SET type = 'content' WHERE type IS NULL")
    op.alter_column('pages', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'type')
    # Dynamically look up the FK constraint name to handle both
    # auto-generated and explicitly named constraints.
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT conname FROM pg_constraint "
        "WHERE conrelid = 'menus'::regclass AND contype = 'f' "
        "AND conkey @> ARRAY["
        "(SELECT attnum FROM pg_attribute "
        "WHERE attrelid = 'menus'::regclass AND attname = 'page_id')"
        "]"
    ))
    constraint_name = result.scalar()
    if constraint_name:
        op.drop_constraint(constraint_name, 'menus', type_='foreignkey')
    op.drop_column('menus', 'page_id')
    # ### end Alembic commands ###
