"""add sort_order to pages

Revision ID: 4ce2b1390180
Revises: 17568737f224
Create Date: 2026-05-25 14:49:24.375975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce2b1390180'
down_revision: Union[str, Sequence[str], None] = '17568737f224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pages', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.execute("UPDATE pages SET sort_order = 0 WHERE sort_order IS NULL")
    op.alter_column('pages', 'sort_order', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'sort_order')
    # ### end Alembic commands ###
