"""add_category_name_desc_to_media

Revision ID: 4db9aff92551
Revises: 4ce2b1390180
Create Date: 2026-05-26 10:37:34.958346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db9aff92551'
down_revision: Union[str, Sequence[str], None] = '4ce2b1390180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('name_zh', sa.String(length=200), nullable=True))
    op.add_column('media', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('media', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'description')
    op.drop_column('media', 'name_en')
    op.drop_column('media', 'name_zh')
    op.drop_column('media', 'category')
    # ### end Alembic commands ###
